services:
  bot:
    container_name: bot
    build: ./bot
    depends_on:
      - redis
    volumes:
      - ./logs:/opt/logs
    restart: always

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: