// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/club"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/clubowner"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/event"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/ignoremailing"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/predicate"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/user"
)

// ClubQuery is the builder for querying Club entities.
type ClubQuery struct {
	config
	ctx                *QueryContext
	order              []club.OrderOption
	inters             []Interceptor
	predicates         []predicate.Club
	withEvents         *EventQuery
	withOwners         *UserQuery
	withIgnoreMailings *IgnoreMailingQuery
	withClubOwners     *ClubOwnerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClubQuery builder.
func (cq *ClubQuery) Where(ps ...predicate.Club) *ClubQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ClubQuery) Limit(limit int) *ClubQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ClubQuery) Offset(offset int) *ClubQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ClubQuery) Unique(unique bool) *ClubQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ClubQuery) Order(o ...club.OrderOption) *ClubQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryEvents chains the current query on the "events" edge.
func (cq *ClubQuery) QueryEvents() *EventQuery {
	query := (&EventClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(club.Table, club.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, club.EventsTable, club.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwners chains the current query on the "owners" edge.
func (cq *ClubQuery) QueryOwners() *UserQuery {
	query := (&UserClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(club.Table, club.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, club.OwnersTable, club.OwnersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIgnoreMailings chains the current query on the "ignore_mailings" edge.
func (cq *ClubQuery) QueryIgnoreMailings() *IgnoreMailingQuery {
	query := (&IgnoreMailingClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(club.Table, club.FieldID, selector),
			sqlgraph.To(ignoremailing.Table, ignoremailing.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, club.IgnoreMailingsTable, club.IgnoreMailingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClubOwners chains the current query on the "club_owners" edge.
func (cq *ClubQuery) QueryClubOwners() *ClubOwnerQuery {
	query := (&ClubOwnerClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(club.Table, club.FieldID, selector),
			sqlgraph.To(clubowner.Table, clubowner.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, club.ClubOwnersTable, club.ClubOwnersColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Club entity from the query.
// Returns a *NotFoundError when no Club was found.
func (cq *ClubQuery) First(ctx context.Context) (*Club, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{club.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ClubQuery) FirstX(ctx context.Context) *Club {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Club ID from the query.
// Returns a *NotFoundError when no Club ID was found.
func (cq *ClubQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{club.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ClubQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Club entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Club entity is found.
// Returns a *NotFoundError when no Club entities are found.
func (cq *ClubQuery) Only(ctx context.Context) (*Club, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{club.Label}
	default:
		return nil, &NotSingularError{club.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ClubQuery) OnlyX(ctx context.Context) *Club {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Club ID in the query.
// Returns a *NotSingularError when more than one Club ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ClubQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{club.Label}
	default:
		err = &NotSingularError{club.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ClubQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Clubs.
func (cq *ClubQuery) All(ctx context.Context) ([]*Club, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Club, *ClubQuery]()
	return withInterceptors[[]*Club](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ClubQuery) AllX(ctx context.Context) []*Club {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Club IDs.
func (cq *ClubQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(club.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ClubQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ClubQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ClubQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ClubQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ClubQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ClubQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClubQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ClubQuery) Clone() *ClubQuery {
	if cq == nil {
		return nil
	}
	return &ClubQuery{
		config:             cq.config,
		ctx:                cq.ctx.Clone(),
		order:              append([]club.OrderOption{}, cq.order...),
		inters:             append([]Interceptor{}, cq.inters...),
		predicates:         append([]predicate.Club{}, cq.predicates...),
		withEvents:         cq.withEvents.Clone(),
		withOwners:         cq.withOwners.Clone(),
		withIgnoreMailings: cq.withIgnoreMailings.Clone(),
		withClubOwners:     cq.withClubOwners.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClubQuery) WithEvents(opts ...func(*EventQuery)) *ClubQuery {
	query := (&EventClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withEvents = query
	return cq
}

// WithOwners tells the query-builder to eager-load the nodes that are connected to
// the "owners" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClubQuery) WithOwners(opts ...func(*UserQuery)) *ClubQuery {
	query := (&UserClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withOwners = query
	return cq
}

// WithIgnoreMailings tells the query-builder to eager-load the nodes that are connected to
// the "ignore_mailings" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClubQuery) WithIgnoreMailings(opts ...func(*IgnoreMailingQuery)) *ClubQuery {
	query := (&IgnoreMailingClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withIgnoreMailings = query
	return cq
}

// WithClubOwners tells the query-builder to eager-load the nodes that are connected to
// the "club_owners" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClubQuery) WithClubOwners(opts ...func(*ClubOwnerQuery)) *ClubQuery {
	query := (&ClubOwnerClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withClubOwners = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Club.Query().
//		GroupBy(club.FieldDeletedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ClubQuery) GroupBy(field string, fields ...string) *ClubGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClubGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = club.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//	}
//
//	client.Club.Query().
//		Select(club.FieldDeletedAt).
//		Scan(ctx, &v)
func (cq *ClubQuery) Select(fields ...string) *ClubSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ClubSelect{ClubQuery: cq}
	sbuild.label = club.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClubSelect configured with the given aggregations.
func (cq *ClubQuery) Aggregate(fns ...AggregateFunc) *ClubSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ClubQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !club.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ClubQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Club, error) {
	var (
		nodes       = []*Club{}
		_spec       = cq.querySpec()
		loadedTypes = [4]bool{
			cq.withEvents != nil,
			cq.withOwners != nil,
			cq.withIgnoreMailings != nil,
			cq.withClubOwners != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Club).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Club{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withEvents; query != nil {
		if err := cq.loadEvents(ctx, query, nodes,
			func(n *Club) { n.Edges.Events = []*Event{} },
			func(n *Club, e *Event) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withOwners; query != nil {
		if err := cq.loadOwners(ctx, query, nodes,
			func(n *Club) { n.Edges.Owners = []*User{} },
			func(n *Club, e *User) { n.Edges.Owners = append(n.Edges.Owners, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withIgnoreMailings; query != nil {
		if err := cq.loadIgnoreMailings(ctx, query, nodes,
			func(n *Club) { n.Edges.IgnoreMailings = []*IgnoreMailing{} },
			func(n *Club, e *IgnoreMailing) { n.Edges.IgnoreMailings = append(n.Edges.IgnoreMailings, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withClubOwners; query != nil {
		if err := cq.loadClubOwners(ctx, query, nodes,
			func(n *Club) { n.Edges.ClubOwners = []*ClubOwner{} },
			func(n *Club, e *ClubOwner) { n.Edges.ClubOwners = append(n.Edges.ClubOwners, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ClubQuery) loadEvents(ctx context.Context, query *EventQuery, nodes []*Club, init func(*Club), assign func(*Club, *Event)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Club)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(event.FieldClubID)
	}
	query.Where(predicate.Event(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(club.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClubID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "club_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *ClubQuery) loadOwners(ctx context.Context, query *UserQuery, nodes []*Club, init func(*Club), assign func(*Club, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Club)
	nids := make(map[uuid.UUID]map[*Club]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(club.OwnersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(club.OwnersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(club.OwnersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(club.OwnersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Club]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "owners" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *ClubQuery) loadIgnoreMailings(ctx context.Context, query *IgnoreMailingQuery, nodes []*Club, init func(*Club), assign func(*Club, *IgnoreMailing)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Club)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ignoremailing.FieldClubID)
	}
	query.Where(predicate.IgnoreMailing(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(club.IgnoreMailingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClubID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "club_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *ClubQuery) loadClubOwners(ctx context.Context, query *ClubOwnerQuery, nodes []*Club, init func(*Club), assign func(*Club, *ClubOwner)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Club)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(clubowner.FieldClubID)
	}
	query.Where(predicate.ClubOwner(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(club.ClubOwnersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClubID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "club_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ClubQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ClubQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(club.Table, club.Columns, sqlgraph.NewFieldSpec(club.FieldID, field.TypeUUID))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, club.FieldID)
		for i := range fields {
			if fields[i] != club.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ClubQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(club.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = club.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClubGroupBy is the group-by builder for Club entities.
type ClubGroupBy struct {
	selector
	build *ClubQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ClubGroupBy) Aggregate(fns ...AggregateFunc) *ClubGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ClubGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClubQuery, *ClubGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ClubGroupBy) sqlScan(ctx context.Context, root *ClubQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClubSelect is the builder for selecting fields of Club entities.
type ClubSelect struct {
	*ClubQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ClubSelect) Aggregate(fns ...AggregateFunc) *ClubSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ClubSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClubQuery, *ClubSelect](ctx, cs.ClubQuery, cs, cs.inters, v)
}

func (cs *ClubSelect) sqlScan(ctx context.Context, root *ClubQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
