// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"

	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/club"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/clubowner"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/user"
)

// ClubOwner is the model entity for the ClubOwner schema.
type ClubOwner struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ClubID holds the value of the "club_id" field.
	ClubID uuid.UUID `json:"club_id,omitempty"`
	// Отправлять ClubOwner-у варнинги
	Warnings bool `json:"warnings,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClubOwnerQuery when eager-loading is set.
	Edges        ClubOwnerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClubOwnerEdges holds the relations/edges for other nodes in the graph.
type ClubOwnerEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Club holds the value of the club edge.
	Club *Club `json:"club,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClubOwnerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ClubOrErr returns the Club value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClubOwnerEdges) ClubOrErr() (*Club, error) {
	if e.Club != nil {
		return e.Club, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: club.Label}
	}
	return nil, &NotLoadedError{edge: "club"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClubOwner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clubowner.FieldWarnings:
			values[i] = new(sql.NullBool)
		case clubowner.FieldDeletedAt, clubowner.FieldCreatedAt, clubowner.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case clubowner.FieldID, clubowner.FieldUserID, clubowner.FieldClubID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClubOwner fields.
func (co *ClubOwner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clubowner.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				co.ID = *value
			}
		case clubowner.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				co.DeletedAt = value.Time
			}
		case clubowner.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				co.CreatedAt = value.Time
			}
		case clubowner.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				co.UpdatedAt = value.Time
			}
		case clubowner.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				co.UserID = *value
			}
		case clubowner.FieldClubID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field club_id", values[i])
			} else if value != nil {
				co.ClubID = *value
			}
		case clubowner.FieldWarnings:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field warnings", values[i])
			} else if value.Valid {
				co.Warnings = value.Bool
			}
		default:
			co.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClubOwner.
// This includes values selected through modifiers, order, etc.
func (co *ClubOwner) Value(name string) (ent.Value, error) {
	return co.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ClubOwner entity.
func (co *ClubOwner) QueryUser() *UserQuery {
	return NewClubOwnerClient(co.config).QueryUser(co)
}

// QueryClub queries the "club" edge of the ClubOwner entity.
func (co *ClubOwner) QueryClub() *ClubQuery {
	return NewClubOwnerClient(co.config).QueryClub(co)
}

// Update returns a builder for updating this ClubOwner.
// Note that you need to call ClubOwner.Unwrap() before calling this method if this ClubOwner
// was returned from a transaction, and the transaction was committed or rolled back.
func (co *ClubOwner) Update() *ClubOwnerUpdateOne {
	return NewClubOwnerClient(co.config).UpdateOne(co)
}

// Unwrap unwraps the ClubOwner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (co *ClubOwner) Unwrap() *ClubOwner {
	_tx, ok := co.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClubOwner is not a transactional entity")
	}
	co.config.driver = _tx.drv
	return co
}

// String implements the fmt.Stringer.
func (co *ClubOwner) String() string {
	var builder strings.Builder
	builder.WriteString("ClubOwner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", co.ID))
	builder.WriteString("deleted_at=")
	builder.WriteString(co.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(co.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(co.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", co.UserID))
	builder.WriteString(", ")
	builder.WriteString("club_id=")
	builder.WriteString(fmt.Sprintf("%v", co.ClubID))
	builder.WriteString(", ")
	builder.WriteString("warnings=")
	builder.WriteString(fmt.Sprintf("%v", co.Warnings))
	builder.WriteByte(')')
	return builder.String()
}

// ClubOwners is a parsable slice of ClubOwner.
type ClubOwners []*ClubOwner
