// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/ignoremailing"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/predicate"
)

// IgnoreMailingDelete is the builder for deleting a IgnoreMailing entity.
type IgnoreMailingDelete struct {
	config
	hooks    []Hook
	mutation *IgnoreMailingMutation
}

// Where appends a list predicates to the IgnoreMailingDelete builder.
func (imd *IgnoreMailingDelete) Where(ps ...predicate.IgnoreMailing) *IgnoreMailingDelete {
	imd.mutation.Where(ps...)
	return imd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (imd *IgnoreMailingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, imd.sqlExec, imd.mutation, imd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (imd *IgnoreMailingDelete) ExecX(ctx context.Context) int {
	n, err := imd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (imd *IgnoreMailingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ignoremailing.Table, sqlgraph.NewFieldSpec(ignoremailing.FieldID, field.TypeUUID))
	if ps := imd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, imd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	imd.mutation.done = true
	return affected, err
}

// IgnoreMailingDeleteOne is the builder for deleting a single IgnoreMailing entity.
type IgnoreMailingDeleteOne struct {
	imd *IgnoreMailingDelete
}

// Where appends a list predicates to the IgnoreMailingDelete builder.
func (imdo *IgnoreMailingDeleteOne) Where(ps ...predicate.IgnoreMailing) *IgnoreMailingDeleteOne {
	imdo.imd.mutation.Where(ps...)
	return imdo
}

// Exec executes the deletion query.
func (imdo *IgnoreMailingDeleteOne) Exec(ctx context.Context) error {
	n, err := imdo.imd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ignoremailing.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (imdo *IgnoreMailingDeleteOne) ExecX(ctx context.Context) {
	if err := imdo.Exec(ctx); err != nil {
		panic(err)
	}
}
