// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/club"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/ignoremailing"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/predicate"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/user"
)

// IgnoreMailingQuery is the builder for querying IgnoreMailing entities.
type IgnoreMailingQuery struct {
	config
	ctx        *QueryContext
	order      []ignoremailing.OrderOption
	inters     []Interceptor
	predicates []predicate.IgnoreMailing
	withUser   *UserQuery
	withClub   *ClubQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IgnoreMailingQuery builder.
func (imq *IgnoreMailingQuery) Where(ps ...predicate.IgnoreMailing) *IgnoreMailingQuery {
	imq.predicates = append(imq.predicates, ps...)
	return imq
}

// Limit the number of records to be returned by this query.
func (imq *IgnoreMailingQuery) Limit(limit int) *IgnoreMailingQuery {
	imq.ctx.Limit = &limit
	return imq
}

// Offset to start from.
func (imq *IgnoreMailingQuery) Offset(offset int) *IgnoreMailingQuery {
	imq.ctx.Offset = &offset
	return imq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (imq *IgnoreMailingQuery) Unique(unique bool) *IgnoreMailingQuery {
	imq.ctx.Unique = &unique
	return imq
}

// Order specifies how the records should be ordered.
func (imq *IgnoreMailingQuery) Order(o ...ignoremailing.OrderOption) *IgnoreMailingQuery {
	imq.order = append(imq.order, o...)
	return imq
}

// QueryUser chains the current query on the "user" edge.
func (imq *IgnoreMailingQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: imq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := imq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := imq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ignoremailing.Table, ignoremailing.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ignoremailing.UserTable, ignoremailing.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(imq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClub chains the current query on the "club" edge.
func (imq *IgnoreMailingQuery) QueryClub() *ClubQuery {
	query := (&ClubClient{config: imq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := imq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := imq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ignoremailing.Table, ignoremailing.FieldID, selector),
			sqlgraph.To(club.Table, club.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ignoremailing.ClubTable, ignoremailing.ClubColumn),
		)
		fromU = sqlgraph.SetNeighbors(imq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IgnoreMailing entity from the query.
// Returns a *NotFoundError when no IgnoreMailing was found.
func (imq *IgnoreMailingQuery) First(ctx context.Context) (*IgnoreMailing, error) {
	nodes, err := imq.Limit(1).All(setContextOp(ctx, imq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ignoremailing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (imq *IgnoreMailingQuery) FirstX(ctx context.Context) *IgnoreMailing {
	node, err := imq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IgnoreMailing ID from the query.
// Returns a *NotFoundError when no IgnoreMailing ID was found.
func (imq *IgnoreMailingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = imq.Limit(1).IDs(setContextOp(ctx, imq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ignoremailing.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (imq *IgnoreMailingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := imq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IgnoreMailing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IgnoreMailing entity is found.
// Returns a *NotFoundError when no IgnoreMailing entities are found.
func (imq *IgnoreMailingQuery) Only(ctx context.Context) (*IgnoreMailing, error) {
	nodes, err := imq.Limit(2).All(setContextOp(ctx, imq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ignoremailing.Label}
	default:
		return nil, &NotSingularError{ignoremailing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (imq *IgnoreMailingQuery) OnlyX(ctx context.Context) *IgnoreMailing {
	node, err := imq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IgnoreMailing ID in the query.
// Returns a *NotSingularError when more than one IgnoreMailing ID is found.
// Returns a *NotFoundError when no entities are found.
func (imq *IgnoreMailingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = imq.Limit(2).IDs(setContextOp(ctx, imq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ignoremailing.Label}
	default:
		err = &NotSingularError{ignoremailing.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (imq *IgnoreMailingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := imq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IgnoreMailings.
func (imq *IgnoreMailingQuery) All(ctx context.Context) ([]*IgnoreMailing, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryAll)
	if err := imq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IgnoreMailing, *IgnoreMailingQuery]()
	return withInterceptors[[]*IgnoreMailing](ctx, imq, qr, imq.inters)
}

// AllX is like All, but panics if an error occurs.
func (imq *IgnoreMailingQuery) AllX(ctx context.Context) []*IgnoreMailing {
	nodes, err := imq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IgnoreMailing IDs.
func (imq *IgnoreMailingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if imq.ctx.Unique == nil && imq.path != nil {
		imq.Unique(true)
	}
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryIDs)
	if err = imq.Select(ignoremailing.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (imq *IgnoreMailingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := imq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (imq *IgnoreMailingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryCount)
	if err := imq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, imq, querierCount[*IgnoreMailingQuery](), imq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (imq *IgnoreMailingQuery) CountX(ctx context.Context) int {
	count, err := imq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (imq *IgnoreMailingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, imq.ctx, ent.OpQueryExist)
	switch _, err := imq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (imq *IgnoreMailingQuery) ExistX(ctx context.Context) bool {
	exist, err := imq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IgnoreMailingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (imq *IgnoreMailingQuery) Clone() *IgnoreMailingQuery {
	if imq == nil {
		return nil
	}
	return &IgnoreMailingQuery{
		config:     imq.config,
		ctx:        imq.ctx.Clone(),
		order:      append([]ignoremailing.OrderOption{}, imq.order...),
		inters:     append([]Interceptor{}, imq.inters...),
		predicates: append([]predicate.IgnoreMailing{}, imq.predicates...),
		withUser:   imq.withUser.Clone(),
		withClub:   imq.withClub.Clone(),
		// clone intermediate query.
		sql:  imq.sql.Clone(),
		path: imq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (imq *IgnoreMailingQuery) WithUser(opts ...func(*UserQuery)) *IgnoreMailingQuery {
	query := (&UserClient{config: imq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	imq.withUser = query
	return imq
}

// WithClub tells the query-builder to eager-load the nodes that are connected to
// the "club" edge. The optional arguments are used to configure the query builder of the edge.
func (imq *IgnoreMailingQuery) WithClub(opts ...func(*ClubQuery)) *IgnoreMailingQuery {
	query := (&ClubClient{config: imq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	imq.withClub = query
	return imq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IgnoreMailing.Query().
//		GroupBy(ignoremailing.FieldDeletedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (imq *IgnoreMailingQuery) GroupBy(field string, fields ...string) *IgnoreMailingGroupBy {
	imq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IgnoreMailingGroupBy{build: imq}
	grbuild.flds = &imq.ctx.Fields
	grbuild.label = ignoremailing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deleted_at,omitempty"`
//	}
//
//	client.IgnoreMailing.Query().
//		Select(ignoremailing.FieldDeletedAt).
//		Scan(ctx, &v)
func (imq *IgnoreMailingQuery) Select(fields ...string) *IgnoreMailingSelect {
	imq.ctx.Fields = append(imq.ctx.Fields, fields...)
	sbuild := &IgnoreMailingSelect{IgnoreMailingQuery: imq}
	sbuild.label = ignoremailing.Label
	sbuild.flds, sbuild.scan = &imq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IgnoreMailingSelect configured with the given aggregations.
func (imq *IgnoreMailingQuery) Aggregate(fns ...AggregateFunc) *IgnoreMailingSelect {
	return imq.Select().Aggregate(fns...)
}

func (imq *IgnoreMailingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range imq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, imq); err != nil {
				return err
			}
		}
	}
	for _, f := range imq.ctx.Fields {
		if !ignoremailing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if imq.path != nil {
		prev, err := imq.path(ctx)
		if err != nil {
			return err
		}
		imq.sql = prev
	}
	return nil
}

func (imq *IgnoreMailingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IgnoreMailing, error) {
	var (
		nodes       = []*IgnoreMailing{}
		_spec       = imq.querySpec()
		loadedTypes = [2]bool{
			imq.withUser != nil,
			imq.withClub != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IgnoreMailing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IgnoreMailing{config: imq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, imq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := imq.withUser; query != nil {
		if err := imq.loadUser(ctx, query, nodes, nil,
			func(n *IgnoreMailing, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := imq.withClub; query != nil {
		if err := imq.loadClub(ctx, query, nodes, nil,
			func(n *IgnoreMailing, e *Club) { n.Edges.Club = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (imq *IgnoreMailingQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*IgnoreMailing, init func(*IgnoreMailing), assign func(*IgnoreMailing, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*IgnoreMailing)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (imq *IgnoreMailingQuery) loadClub(ctx context.Context, query *ClubQuery, nodes []*IgnoreMailing, init func(*IgnoreMailing), assign func(*IgnoreMailing, *Club)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*IgnoreMailing)
	for i := range nodes {
		fk := nodes[i].ClubID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(club.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "club_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (imq *IgnoreMailingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := imq.querySpec()
	_spec.Node.Columns = imq.ctx.Fields
	if len(imq.ctx.Fields) > 0 {
		_spec.Unique = imq.ctx.Unique != nil && *imq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, imq.driver, _spec)
}

func (imq *IgnoreMailingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ignoremailing.Table, ignoremailing.Columns, sqlgraph.NewFieldSpec(ignoremailing.FieldID, field.TypeUUID))
	_spec.From = imq.sql
	if unique := imq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if imq.path != nil {
		_spec.Unique = true
	}
	if fields := imq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ignoremailing.FieldID)
		for i := range fields {
			if fields[i] != ignoremailing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if imq.withUser != nil {
			_spec.Node.AddColumnOnce(ignoremailing.FieldUserID)
		}
		if imq.withClub != nil {
			_spec.Node.AddColumnOnce(ignoremailing.FieldClubID)
		}
	}
	if ps := imq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := imq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := imq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := imq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (imq *IgnoreMailingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(imq.driver.Dialect())
	t1 := builder.Table(ignoremailing.Table)
	columns := imq.ctx.Fields
	if len(columns) == 0 {
		columns = ignoremailing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if imq.sql != nil {
		selector = imq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if imq.ctx.Unique != nil && *imq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range imq.predicates {
		p(selector)
	}
	for _, p := range imq.order {
		p(selector)
	}
	if offset := imq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := imq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IgnoreMailingGroupBy is the group-by builder for IgnoreMailing entities.
type IgnoreMailingGroupBy struct {
	selector
	build *IgnoreMailingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (imgb *IgnoreMailingGroupBy) Aggregate(fns ...AggregateFunc) *IgnoreMailingGroupBy {
	imgb.fns = append(imgb.fns, fns...)
	return imgb
}

// Scan applies the selector query and scans the result into the given value.
func (imgb *IgnoreMailingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, imgb.build.ctx, ent.OpQueryGroupBy)
	if err := imgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IgnoreMailingQuery, *IgnoreMailingGroupBy](ctx, imgb.build, imgb, imgb.build.inters, v)
}

func (imgb *IgnoreMailingGroupBy) sqlScan(ctx context.Context, root *IgnoreMailingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(imgb.fns))
	for _, fn := range imgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*imgb.flds)+len(imgb.fns))
		for _, f := range *imgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*imgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := imgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IgnoreMailingSelect is the builder for selecting fields of IgnoreMailing entities.
type IgnoreMailingSelect struct {
	*IgnoreMailingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ims *IgnoreMailingSelect) Aggregate(fns ...AggregateFunc) *IgnoreMailingSelect {
	ims.fns = append(ims.fns, fns...)
	return ims
}

// Scan applies the selector query and scans the result into the given value.
func (ims *IgnoreMailingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ims.ctx, ent.OpQuerySelect)
	if err := ims.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IgnoreMailingQuery, *IgnoreMailingSelect](ctx, ims.IgnoreMailingQuery, ims, ims.inters, v)
}

func (ims *IgnoreMailingSelect) sqlScan(ctx context.Context, root *IgnoreMailingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ims.fns))
	for _, fn := range ims.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ims.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ims.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
