// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/google/uuid"

	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/club"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/clubowner"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/event"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/eventparticipant"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/ignoremailing"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/notification"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/pass"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/schema"
	"github.com/Badsnus/cu-clubs-bot/bot/internal/adapters/secondary/postgres/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clubMixin := schema.Club{}.Mixin()
	clubMixinHooks0 := clubMixin[0].Hooks()
	club.Hooks[0] = clubMixinHooks0[0]
	clubMixinInters0 := clubMixin[0].Interceptors()
	club.Interceptors[0] = clubMixinInters0[0]
	clubMixinFields1 := clubMixin[1].Fields()
	_ = clubMixinFields1
	clubFields := schema.Club{}.Fields()
	_ = clubFields
	// clubDescCreatedAt is the schema descriptor for created_at field.
	clubDescCreatedAt := clubMixinFields1[0].Descriptor()
	// club.DefaultCreatedAt holds the default value on creation for the created_at field.
	club.DefaultCreatedAt = clubDescCreatedAt.Default.(time.Time)
	// clubDescUpdatedAt is the schema descriptor for updated_at field.
	clubDescUpdatedAt := clubMixinFields1[1].Descriptor()
	// club.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	club.DefaultUpdatedAt = clubDescUpdatedAt.Default.(time.Time)
	// club.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	club.UpdateDefaultUpdatedAt = clubDescUpdatedAt.UpdateDefault.(func() time.Time)
	// clubDescLink is the schema descriptor for link field.
	clubDescLink := clubFields[3].Descriptor()
	// club.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	club.LinkValidator = clubDescLink.Validators[0].(func(string) error)
	// clubDescVisibleInTour is the schema descriptor for visible_in_tour field.
	clubDescVisibleInTour := clubFields[6].Descriptor()
	// club.DefaultVisibleInTour holds the default value on creation for the visible_in_tour field.
	club.DefaultVisibleInTour = clubDescVisibleInTour.Default.(bool)
	// clubDescQrAllowed is the schema descriptor for qr_allowed field.
	clubDescQrAllowed := clubFields[8].Descriptor()
	// club.DefaultQrAllowed holds the default value on creation for the qr_allowed field.
	club.DefaultQrAllowed = clubDescQrAllowed.Default.(bool)
	// clubDescID is the schema descriptor for id field.
	clubDescID := clubFields[0].Descriptor()
	// club.DefaultID holds the default value on creation for the id field.
	club.DefaultID = clubDescID.Default.(func() uuid.UUID)
	clubownerMixin := schema.ClubOwner{}.Mixin()
	clubownerMixinHooks0 := clubownerMixin[0].Hooks()
	clubowner.Hooks[0] = clubownerMixinHooks0[0]
	clubownerMixinInters0 := clubownerMixin[0].Interceptors()
	clubowner.Interceptors[0] = clubownerMixinInters0[0]
	clubownerMixinFields1 := clubownerMixin[1].Fields()
	_ = clubownerMixinFields1
	clubownerFields := schema.ClubOwner{}.Fields()
	_ = clubownerFields
	// clubownerDescCreatedAt is the schema descriptor for created_at field.
	clubownerDescCreatedAt := clubownerMixinFields1[0].Descriptor()
	// clubowner.DefaultCreatedAt holds the default value on creation for the created_at field.
	clubowner.DefaultCreatedAt = clubownerDescCreatedAt.Default.(time.Time)
	// clubownerDescUpdatedAt is the schema descriptor for updated_at field.
	clubownerDescUpdatedAt := clubownerMixinFields1[1].Descriptor()
	// clubowner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	clubowner.DefaultUpdatedAt = clubownerDescUpdatedAt.Default.(time.Time)
	// clubowner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	clubowner.UpdateDefaultUpdatedAt = clubownerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// clubownerDescWarnings is the schema descriptor for warnings field.
	clubownerDescWarnings := clubownerFields[3].Descriptor()
	// clubowner.DefaultWarnings holds the default value on creation for the warnings field.
	clubowner.DefaultWarnings = clubownerDescWarnings.Default.(bool)
	// clubownerDescID is the schema descriptor for id field.
	clubownerDescID := clubownerFields[0].Descriptor()
	// clubowner.DefaultID holds the default value on creation for the id field.
	clubowner.DefaultID = clubownerDescID.Default.(func() uuid.UUID)
	eventMixin := schema.Event{}.Mixin()
	eventMixinHooks0 := eventMixin[0].Hooks()
	event.Hooks[0] = eventMixinHooks0[0]
	eventMixinInters0 := eventMixin[0].Interceptors()
	event.Interceptors[0] = eventMixinInters0[0]
	eventMixinFields1 := eventMixin[1].Fields()
	_ = eventMixinFields1
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventMixinFields1[0].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(time.Time)
	// eventDescUpdatedAt is the schema descriptor for updated_at field.
	eventDescUpdatedAt := eventMixinFields1[1].Descriptor()
	// event.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	event.DefaultUpdatedAt = eventDescUpdatedAt.Default.(time.Time)
	// event.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	event.UpdateDefaultUpdatedAt = eventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// eventDescMaxParticipants is the schema descriptor for max_participants field.
	eventDescMaxParticipants := eventFields[9].Descriptor()
	// event.MaxParticipantsValidator is a validator for the "max_participants" field. It is called by the builders before save.
	event.MaxParticipantsValidator = eventDescMaxParticipants.Validators[0].(func(int) error)
	// eventDescExpectedParticipants is the schema descriptor for expected_participants field.
	eventDescExpectedParticipants := eventFields[10].Descriptor()
	// event.ExpectedParticipantsValidator is a validator for the "expected_participants" field. It is called by the builders before save.
	event.ExpectedParticipantsValidator = eventDescExpectedParticipants.Validators[0].(func(int) error)
	// eventDescPassRequired is the schema descriptor for pass_required field.
	eventDescPassRequired := eventFields[14].Descriptor()
	// event.DefaultPassRequired holds the default value on creation for the pass_required field.
	event.DefaultPassRequired = eventDescPassRequired.Default.(bool)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	eventparticipantMixin := schema.EventParticipant{}.Mixin()
	eventparticipantMixinHooks0 := eventparticipantMixin[0].Hooks()
	eventparticipant.Hooks[0] = eventparticipantMixinHooks0[0]
	eventparticipantMixinInters0 := eventparticipantMixin[0].Interceptors()
	eventparticipant.Interceptors[0] = eventparticipantMixinInters0[0]
	eventparticipantMixinFields1 := eventparticipantMixin[1].Fields()
	_ = eventparticipantMixinFields1
	eventparticipantFields := schema.EventParticipant{}.Fields()
	_ = eventparticipantFields
	// eventparticipantDescCreatedAt is the schema descriptor for created_at field.
	eventparticipantDescCreatedAt := eventparticipantMixinFields1[0].Descriptor()
	// eventparticipant.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventparticipant.DefaultCreatedAt = eventparticipantDescCreatedAt.Default.(time.Time)
	// eventparticipantDescUpdatedAt is the schema descriptor for updated_at field.
	eventparticipantDescUpdatedAt := eventparticipantMixinFields1[1].Descriptor()
	// eventparticipant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	eventparticipant.DefaultUpdatedAt = eventparticipantDescUpdatedAt.Default.(time.Time)
	// eventparticipant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	eventparticipant.UpdateDefaultUpdatedAt = eventparticipantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// eventparticipantDescID is the schema descriptor for id field.
	eventparticipantDescID := eventparticipantFields[0].Descriptor()
	// eventparticipant.DefaultID holds the default value on creation for the id field.
	eventparticipant.DefaultID = eventparticipantDescID.Default.(func() uuid.UUID)
	ignoremailingMixin := schema.IgnoreMailing{}.Mixin()
	ignoremailingMixinHooks0 := ignoremailingMixin[0].Hooks()
	ignoremailing.Hooks[0] = ignoremailingMixinHooks0[0]
	ignoremailingMixinInters0 := ignoremailingMixin[0].Interceptors()
	ignoremailing.Interceptors[0] = ignoremailingMixinInters0[0]
	ignoremailingMixinFields1 := ignoremailingMixin[1].Fields()
	_ = ignoremailingMixinFields1
	ignoremailingFields := schema.IgnoreMailing{}.Fields()
	_ = ignoremailingFields
	// ignoremailingDescCreatedAt is the schema descriptor for created_at field.
	ignoremailingDescCreatedAt := ignoremailingMixinFields1[0].Descriptor()
	// ignoremailing.DefaultCreatedAt holds the default value on creation for the created_at field.
	ignoremailing.DefaultCreatedAt = ignoremailingDescCreatedAt.Default.(time.Time)
	// ignoremailingDescUpdatedAt is the schema descriptor for updated_at field.
	ignoremailingDescUpdatedAt := ignoremailingMixinFields1[1].Descriptor()
	// ignoremailing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ignoremailing.DefaultUpdatedAt = ignoremailingDescUpdatedAt.Default.(time.Time)
	// ignoremailing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ignoremailing.UpdateDefaultUpdatedAt = ignoremailingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ignoremailingDescID is the schema descriptor for id field.
	ignoremailingDescID := ignoremailingFields[0].Descriptor()
	// ignoremailing.DefaultID holds the default value on creation for the id field.
	ignoremailing.DefaultID = ignoremailingDescID.Default.(func() uuid.UUID)
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinHooks0 := notificationMixin[0].Hooks()
	notification.Hooks[0] = notificationMixinHooks0[0]
	notificationMixinInters0 := notificationMixin[0].Interceptors()
	notification.Interceptors[0] = notificationMixinInters0[0]
	notificationMixinFields1 := notificationMixin[1].Fields()
	_ = notificationMixinFields1
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationMixinFields1[0].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationMixinFields1[1].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	passMixin := schema.Pass{}.Mixin()
	passMixinFields0 := passMixin[0].Fields()
	_ = passMixinFields0
	passFields := schema.Pass{}.Fields()
	_ = passFields
	// passDescCreatedAt is the schema descriptor for created_at field.
	passDescCreatedAt := passMixinFields0[0].Descriptor()
	// pass.DefaultCreatedAt holds the default value on creation for the created_at field.
	pass.DefaultCreatedAt = passDescCreatedAt.Default.(time.Time)
	// passDescUpdatedAt is the schema descriptor for updated_at field.
	passDescUpdatedAt := passMixinFields0[1].Descriptor()
	// pass.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pass.DefaultUpdatedAt = passDescUpdatedAt.Default.(time.Time)
	// pass.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pass.UpdateDefaultUpdatedAt = passDescUpdatedAt.UpdateDefault.(func() time.Time)
	// passDescEmailSent is the schema descriptor for email_sent field.
	passDescEmailSent := passFields[10].Descriptor()
	// pass.DefaultEmailSent holds the default value on creation for the email_sent field.
	pass.DefaultEmailSent = passDescEmailSent.Default.(bool)
	// passDescTelegramSent is the schema descriptor for telegram_sent field.
	passDescTelegramSent := passFields[11].Descriptor()
	// pass.DefaultTelegramSent holds the default value on creation for the telegram_sent field.
	pass.DefaultTelegramSent = passDescTelegramSent.Default.(bool)
	// passDescID is the schema descriptor for id field.
	passDescID := passFields[0].Descriptor()
	// pass.DefaultID holds the default value on creation for the id field.
	pass.DefaultID = passDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescTelegramID is the schema descriptor for telegram_id field.
	userDescTelegramID := userFields[1].Descriptor()
	// user.TelegramIDValidator is a validator for the "telegram_id" field. It is called by the builders before save.
	user.TelegramIDValidator = userDescTelegramID.Validators[0].(func(int64) error)
	// userDescIsBanned is the schema descriptor for is_banned field.
	userDescIsBanned := userFields[9].Descriptor()
	// user.DefaultIsBanned holds the default value on creation for the is_banned field.
	user.DefaultIsBanned = userDescIsBanned.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.0"                                         // Version of ent codegen.
	Sum     = "h1:EO3Z9aZ5bXJatJeGqu/EVdnNr6K4mRq3rWe5owt0MC4=" // Sum of ent codegen.
)
