# простой конфиг файл, ВРЕМЕННЫЙ, при рефакторинге - использовать .golangci.yml.new

version: 2

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: false

  errcheck:
    check-type-assertions: false
    check-blank: false

linters:
  disable-all: true
  enable:
    # Только базовые проверки
    - errcheck
    - govet
    - staticcheck

issues:
  exclude:
    # Исключаем часто встречающиеся ошибки
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print.*|os\.(Un)?Setenv). is not checked

  exclude-rules:
    # Исключаем проверки для тестовых файлов
    - path: _test\.go
      linters:
        - errcheck
        - govet
        - staticcheck
