service:
  database:
    host: "database"
    user: "user"
    password: "password"
    port: 5400
    name: "database"

  redis:
    host: "redis"
    password: "password"
    port: 6380

bot:
  token: "BOT_TOKEN"
  channel-id: -1002480092513 # id канала на который необходимо подписаться начинающийся с -100
  admin-ids:
    - 5863804676

settings:
  debug: false # дебаг мод
  timezone: "GMT+3" # часовой пояс для логирования
  log-to-file: true # логирование в файл
  logs-dir: "./logs"

