// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// ClubOwner is the predicate function for clubowner builders.
type ClubOwner func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// EventParticipant is the predicate function for eventparticipant builders.
type EventParticipant func(*sql.Selector)

// IgnoreMailing is the predicate function for ignoremailing builders.
type IgnoreMailing func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Pass is the predicate function for pass builders.
type Pass func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
