name: Go Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "bot/**"
      - "Makefile"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.2

      - name: Install tools
        run: |
          make install-tools

      - name: Run Go tests
        run: |
          make go-test

      - name: Run Go tests with coverage
        run: |
          make go-test-coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: bot/coverage.html
